import { useEffect, useRef, useState } from 'react';
import { Link, NavLink, useLocation } from 'react-router-dom';
import { motion, useReducedMotion } from 'motion/react';
import { ArrowUpRight, ArrowDownRight, Menu, X } from 'lucide-react';
import { useLocale, LanguageSwitch } from './locale';
import { ThemeSwitch, SocialLinks, Newsletter } from './Engagement';
import { useProjects } from './ProjectsContext';
import { AnimatedHeading } from './TypedReveal';
import BusinessEngine from './BusinessEngine';
import LabBoot from './LabBoot';
import SignalField from './SignalField';
import BrandArchive from './BrandArchive';
import HandprintWall from './HandprintWall';
import { StoryPeople } from './People';
import './Existence.css';

function Arr({down=false}) { return down?<ArrowDownRight size={18}/>:<ArrowUpRight size={18}/>; }
function Tag({children}) { return <div className="ex-tag">{children}</div>; }
function Reveal({children,className=''}) {const reduce=useReducedMotion();return <motion.div className={className} initial={reduce?false:{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.08}} transition={{duration:1.1,ease:[.22,1,.36,1]}}>{children}</motion.div>;}
function Go({to='/contact',children,solid=false}) {return <Link className={solid?'ex-pill ex-dark':'ex-link'} to={to}>{children}<Arr/></Link>;}
const links=[['/','Home','Accueil','الرئيسية'],['/work','Our work','Nos projets','أعمالنا'],['/services','Our services','Nos services','خدماتنا'],['/about','Who we are','Qui sommes-nous','من نحن'],['/join-us','Join us','Rejoignez-nous','انضم إلينا'],['/contact','Contact us','Contactez-nous','تواصل معنا'],['/lab','Liminal Lab','Liminal Lab','مختبر ليمينال']];
export function ExistenceHeader() {
 const {t}=useLocale(),{pathname}=useLocation(),[open,setOpen]=useState(false),dialog=useRef(null),trigger=useRef(null);
 function close(){dialog.current?.close();setOpen(false);}
 useEffect(()=>{close();},[pathname]);
 useEffect(()=>{if(!open)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous;};},[open]);
 return <><a className="skip-link" href="#main">{t('Aller au contenu','Skip to content','انتقل إلى المحتوى')}</a><header className="ex-header">
 <Link className="ex-logo" to="/" aria-label="LIMINAL — Home" onClick={e=>{if(pathname==='/'){e.preventDefault();window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}}}><img src="/brand/wordmark.svg" alt="LIMINAL"/></Link>
 <button ref={trigger} className="ex-pill ex-menu-trigger" aria-expanded={open} aria-controls="ex-menu" onClick={()=>{dialog.current.showModal();setOpen(true);}}><Menu size={16}/>{t('Menu','Menu','القائمة')}</button>
 <Link className="ex-pill ex-dark ex-header-cta" to="/contact">{t('Démarrer un projet','Start a project','ابدأ مشروعاً')}<Arr/></Link>
 </header><dialog id="ex-menu" ref={dialog} className="ex-menu" aria-label={t('Navigation','Navigation','التنقل')} onClose={()=>{setOpen(false);trigger.current?.focus({preventScroll:true});}} onClick={e=>{if(e.target===dialog.current)close();}}>
 <div className="ex-menu-surface"><div className="ex-menu-top"><Tag>LIMINAL / {t('EXPLORER','EXPLORE','استكشف')}</Tag><button autoFocus className="ex-icon" onClick={close} aria-label={t('Fermer le menu','Close menu','إغلاق القائمة')}><X size={20}/></button></div>
 <nav>{links.map(([to,en,fr,ar],i)=><NavLink key={to} to={to} end onClick={close}><small>0{i+1}</small>{t(fr,en,ar)}<Arr/></NavLink>)}</nav>
 <div className="ex-menu-settings"><LanguageSwitch/><ThemeSwitch/><Go solid>{t('Démarrer un projet','Start a project','ابدأ مشروعاً')}</Go></div>
 </div></dialog></>;
}
export function ExistenceFooter(){const {t}=useLocale();return <footer className="ex-footer ex-wrap"><div className="ex-footer-main"><div><Link className="ex-logo" to="/"><img src="/brand/wordmark.svg" alt="LIMINAL"/></Link><p>{t('Compagnie créative indépendante.','Independent creative company.','شركة إبداعية مستقلة.')}<br/>Tunis / Everywhere.</p></div><nav aria-label="Footer">{links.map(([to,en,fr,ar])=><Link key={to} to={to}>{t(fr,en,ar)}</Link>)}<SocialLinks only={["instagram"]}/></nav></div><div className="ex-footer-bottom"><span>FROM A TRACE.<br/>TO A MOVEMENT.</span><details><summary>{t('Restons en lien','Stay in the loop','لنبقَ على تواصل')}</summary><Newsletter/><Link to="/join-us">{t('Créer avec nous','Enter the orbit','أبدع معنا')}</Link><Link to="/feedback">{t('Un retour sur le site ?','Feedback on this place?','رأيك في الموقع؟')}</Link></details><span>© {new Date().getFullYear()} LIMINAL</span></div></footer>;}
function WorkObjects({all=false}) {const {projects,loading,error,refresh}=useProjects(),{t}=useLocale();const shown=all?projects:projects.filter(p=>p.featured).slice(0,4);return <>{loading&&<p role="status">{t('Chargement…','Loading…','جار التحميل…')}</p>}{error&&<p role="alert">{t('Les projets sont indisponibles.','Projects are unavailable.','الأعمال غير متاحة.')} <button onClick={refresh}>{t('Réessayer','Retry','أعد المحاولة')}</button></p>}<div className={'ex-work-objects '+(all?'ex-work-all':'')}>{shown.map((p,i)=><Reveal key={p.slug} className={'ex-work-object object-'+i}><Link to={'/work/'+p.slug} className="ex-work-media">{p.visual==='video'?<video src={p.media} poster={p.poster} muted playsInline preload="none" aria-label={p.title}/>:<img src={p.media} alt={p.title} loading="lazy"/>}<span className="ex-media-arrow"><Arr/></span><span className="ex-case-link">{t("Voir l’étude de cas","View case study","شاهد دراسة المشروع")}</span></Link><div className="ex-work-caption"><div><h3><Link to={'/work/'+p.slug}>{p.title}</Link></h3><p>{p.description}</p></div><small>{[p.client,p.year].filter(Boolean).join(' / ')}<br/>{p.category}</small></div></Reveal>)}</div></>;}
export function WorkPage(){const {t}=useLocale();return <div className="existence"><section className="ex-wrap ex-page-opening"><Tag>01 / {t('POUR LES AUTRES','FOR OTHERS','للآخرين')}</Tag><AnimatedHeading as="h1">{t('DES IDÉES','THINGS WE','أفكار')}<br/><em>{t('DEVENUES RÉELLES.','HELPED EXIST.','صارت واقعاً.')}</em></AnimatedHeading><p>{t('Des idées que nous avons aidées à devenir réelles. Chaque projet choisit sa propre forme.','Ideas we helped cross the line into reality. Every project finds its own form.','أفكار ساعدناها على أن تصبح واقعاً. لكل مشروع شكله الخاص.')}</p></section><section className="ex-wrap"><WorkObjects all/></section><FinalCall/></div>;}
function LabIntro({page=false}){const {t}=useLocale();const headingLevel=page?"h1":"h2";return <><Tag>02 / {t('POUR PERSONNE','FOR NO ONE','بلا طلب')}</Tag><AnimatedHeading as={headingLevel}>{t('PAS DE BRIEF.','NO BRIEF.','بلا موجز.')}<br/>{t('PAS DE PERMISSION.','NO PERMISSION.','بلا إذن.')}</AnimatedHeading><p className="ex-lab-name">LIMINAL LAB</p><p>{t('Le Lab, c’est là où nous fabriquons avant qu’on nous le demande.','The Lab is where we make things before anyone asks for them.','هنا نصنع أشياء قبل أن يطلبها أحد.')}</p></>;}
export function LabPage(){return <LabBoot><LabContent/></LabBoot>;}
function LabContent(){const {t}=useLocale(),[strength,setStrength]=useState(1),[paused,setPaused]=useState(false);return <div className="existence"><section className="ex-wrap ex-page-opening ex-lab-opening"><LabIntro page/></section><section className="ex-wrap ex-notebook"><div className="ex-lab-meta"><Tag>LAB_001 / 05.10.2026</Tag><span>{t('ÉTUDE EN COURS · CODE / MOTION','IN PROGRESS · CODE / MOTION','تجربة جارية · برمجة / حركة')}</span></div><div className="ex-signal-play"><SignalField study strength={strength} paused={paused}/><span>01 — SIGNAL, BEFORE FORM.</span></div><div className="ex-lab-controls"><label>{t('Tension','Tension','التوتر')}<input type="range" min="0" max="3" step=".1" value={strength} onChange={e=>setStrength(Number(e.target.value))}/></label><button className="ex-link" aria-pressed={paused} onClick={()=>setPaused(!paused)}>{paused?t('Reprendre','Resume','متابعة'):t('Pause','Pause','إيقاف')}</button><button className="ex-link" onClick={()=>{setStrength(1);setPaused(false);}}>{t('Réinitialiser','Reset','إعادة ضبط')}</button></div><div className="ex-note"><AnimatedHeading>{t('Une pensée prend forme.','A thought taking shape.','فكرة تأخذ شكلها.')}</AnimatedHeading><p>{t('Le fond de ce site, sorti de son cadre. Des lignes, un mouvement lent, votre curseur. Une étude vivante, pas un produit fini.','The background of this site, taken out of its frame. Lines, slow movement, your cursor. A living study, not a finished product.','خلفية هذا الموقع خارج إطارها. خطوط وحركة بطيئة ومؤشرك. تجربة حية، وليست منتجاً نهائياً.')}</p><small>{t('Sur mobile et en mouvement réduit : une trace fixe, réglable.','On mobile and with reduced motion: a still, adjustable trace.','على الهاتف ومع تقليل الحركة: أثر ثابت قابل للتعديل.')}</small></div></section><section className="ex-wrap ex-lab-end"><p>{t('Certaines expériences restent ici. D’autres trouvent une sortie.','Some experiments stay here. Others find a way out.','بعض التجارب تبقى هنا. وأخرى تجد مخرجاً.')}</p><Go to="/drops">{t('Voir les drops','See the drops','شاهد الإصدارات')}</Go></section></div>;}
export function DropsPage(){const {t}=useLocale();return <div className="existence"><section className="ex-drop-page ex-wrap"><Tag>DROP_001</Tag><AnimatedHeading as="h1">{t('PAS ENCORE.','NOT YET.','ليس بعد.')}</AnimatedHeading><div className="ex-empty-object" aria-hidden="true"><span>001</span></div><p>{t('Quelque chose finira par s’échapper du Lab.','Something will escape the Lab eventually.','شيء ما سيخرج من المختبر يوماً.')}</p><Go to="/lab">{t('Entrer dans le Lab','Enter the Lab','ادخل المختبر')}</Go></section></div>;}
export function HowThingsEscape(){const {t}=useLocale();const steps=[['FIND IT.','TROUVER.','نجدها.','What is actually worth making?','Qu’est-ce qui mérite vraiment d’exister ?','ما الذي يستحق أن نصنعه؟'],['SHAPE IT.','DONNER FORME.','نشكلها.','Give the idea a world, a voice and a direction.','Donner à l’idée un monde, une voix, une direction.','نمنح الفكرة عالماً وصوتاً واتجاهاً.'],['MAKE IT.','FABRIQUER.','نصنعها.','Film it. Design it. Code it. Build it. Whatever it needs.','Filmer. Designer. Coder. Construire. Ce dont l’idée a besoin.','نصورها. نصممها. نبرمجها. نبنيها. بكل ما تحتاجه.'],['RELEASE IT.','LA LANCER.','نطلقها.','Turn the thing into a moment people can see, feel and remember.','En faire un moment que l’on voit, ressent et retient.','نحولها إلى لحظة يراها الناس ويشعرون بها ويتذكرونها.']];return <section className="ex-wrap ex-method" id="how"><Tag>04 / {t('COMMENT LES IDÉES S’ÉCHAPPENT','HOW THINGS ESCAPE','كيف تخرج الأفكار')}</Tag>{steps.map(([en,fr,ar,den,dfr,dar],i)=><Reveal key={en} className="ex-method-row"><span>0{i+1}</span><AnimatedHeading>{t(fr,en,ar)}</AnimatedHeading><p>{t(dfr,den,dar)}</p></Reveal>)}</section>;}
function Story({full=false}){const {t}=useLocale();return <section className="ex-wrap ex-story"><Tag>05 / WHY LIMINAL</Tag><Reveal><AnimatedHeading>{t('TOUT A COMMENCÉ','IT STARTED','بدأ الأمر')}<br/>{t('PAR LE DESIGN.','WITH DESIGN.','بالتصميم.')}</AnimatedHeading><p className="ex-serif">{t('Puis le design n’a plus suffi.','Then design stopped being enough.','ثم لم يعد التصميم وحده يكفي.')}</p></Reveal><div className="ex-story-copy"><p>{t('Le travail a débordé du cadre. Le design est devenu mouvement. Le mouvement est devenu film. Le film a touché au son, au code, à la technologie, à l’IA et aux objets.','Then the work kept escaping the frame. Design became motion. Motion became film. Film touched sound, code, technology, AI and physical things.','خرج العمل من الإطار. صار التصميم حركة، والحركة فيلماً. والتقى الفيلم بالصوت والبرمجة والتكنولوجيا والذكاء الاصطناعي والأشياء الملموسة.')}</p><p>{t('Choisir une seule case devenait trop étroit. Alors nous avons arrêté d’en choisir une.','Choosing one box started to feel more limiting than useful. So we stopped choosing one.','صار اختيار خانة واحدة قيداً. فتوقفنا عن الاختيار.')}</p><p>{t('LIMINAL est devenu cet espace entre une pensée inachevée et le moment où elle devient réelle. Aujourd’hui, nous créons avec des clients, expérimentons sans eux et construisons nos propres choses.','LIMINAL became the place between an unfinished thought and the moment it becomes real. Today we make things with clients, experiment without them, and build things of our own.','صارت ليمينال المساحة بين فكرة لم تكتمل ولحظة تصبح فيها حقيقية. اليوم نصنع مع عملاء، ونجرب دونهم، ونبني أشياء تخصنا.')}</p>{!full&&<Go to="/about">{t('Pourquoi LIMINAL','Why LIMINAL','لماذا ليمينال')}</Go>}</div></section>;}
function Movement(){const {t}=useLocale();return <section className="ex-wrap ex-movement"><Tag>06 / {t('PAS UN DÉPARTEMENT','NOT A DEPARTMENT','لسنا قسماً')}</Tag><Reveal><AnimatedHeading>{t('CRÉER AVEC','BUILD WITH','ابنِ مع')}<br/><em>{t('DES GENS À PART.','STRANGE PEOPLE.','أناس مختلفين.')}</em></AnimatedHeading></Reveal><p>{t('Pas une pièce remplie des mêmes profils. Un réseau en mouvement : réalisateurs, designers, développeurs, photographes, artistes 3D, musiciens, makers, auteurs — et ceux qu’on ne sait pas classer.','Not a room full of identical job titles. A moving network of directors, designers, developers, photographers, 3D artists, musicians, makers, writers, artists — and people who are difficult to categorize.','لسنا غرفة من المسميات المتشابهة. شبكة تتحرك: مخرجون ومصممون ومبرمجون ومصورون وفنانو 3D وموسيقيون وصناع وكتاب وفنانون، وأناس يصعب تصنيفهم.')}</p><p className="ex-serif">{t('L’équipe change avec l’idée. Le regard reste.','The team changes with the idea. The taste does not.','يتغير الفريق مع الفكرة. ولا تتغير الرؤية.')}</p><small>{t('Projet après projet. Expérience après expérience. Drop après drop.','Project by project. Experiment by experiment. Drop by drop.','مشروعاً بعد مشروع. تجربة بعد تجربة. إصداراً بعد إصدار.')}</small><Go to="/join-us">{t('Entrer dans l’orbite','Enter the orbit','ادخل المدار')}</Go></section>;}
export function AboutPage(){const {t}=useLocale();return <div className="existence"><div className="ex-about-top ex-wrap"><Tag>{t('COMPAGNIE CRÉATIVE INDÉPENDANTE','INDEPENDENT CREATIVE COMPANY','شركة إبداعية مستقلة')}</Tag><AnimatedHeading as="h1">{t('ENTRE','BETWEEN','بين')}<br/>“WHAT IF?”<br/><em>“IT EXISTS.”</em></AnimatedHeading></div><Story full/><StoryPeople/><Movement/><BrandArchive/><HandprintWall/><FinalCall/></div>;}
export function FinalCall(){const {t}=useLocale();return <section className="ex-final"><div className="ex-wrap"><Tag>{t('ON COMMENCE ICI.','WE START HERE.','نبدأ هنا.')}</Tag><Reveal><AnimatedHeading>{t('APPORTEZ-NOUS','BRING US','أحضر لنا')}<br/>{t('LA VERSION','THE UNFINISHED','النسخة')}<br/>{t('INACHEVÉE.','VERSION.','غير المكتملة.')}</AnimatedHeading></Reveal><p className="ex-serif">{t('Un vocal suffit.','A voice note is enough.','رسالة صوتية تكفي.')}</p><div className="ex-final-bottom"><p>{t('Un prototype. Une date. Un croquis. Un mauvais deck. Une drôle d’idée. On part de là.','A prototype. A launch date. A sketch. A bad deck. A strange thought. We’ll start there.','نموذج أولي. موعد إطلاق. رسم. عرض غير مكتمل. فكرة غريبة. نبدأ من هناك.')}</p><Go solid>{t('Démarrer un projet','Start a project','ابدأ مشروعاً')}</Go></div></div></section>;}
export default function ExistenceHome(){const {t}=useLocale(),[touched,setTouched]=useState(false);return <div className="existence"><section className="ex-hero"><SignalField/><div className="ex-wrap ex-hero-content"><Tag>{t('COMPAGNIE CRÉATIVE INDÉPENDANTE','INDEPENDENT CREATIVE COMPANY','شركة إبداعية مستقلة')}<br/>TUNIS / EVERYWHERE</Tag><Reveal><AnimatedHeading as="h1">{t('ON FAIT','WE MAKE','نمنح الأشياء')}<br/>{t('EXISTER LES IDÉES.','THINGS EXIST.','وجوداً.')}</AnimatedHeading></Reveal><p className="ex-hero-thought">{t('Entre « et si ? »','Between “what if?”','بين «ماذا لو؟»')}<br/><em>{t('et « ça existe ».','and “it exists.”','و«صار حقيقة».')}</em></p><p className="ex-hero-description">{t('LIMINAL transforme les idées inachevées en lancements, univers, films, produits et expériences.','LIMINAL turns unfinished ideas into launches, worlds, films, products and experiments.','تحول ليمينال الأفكار غير المكتملة إلى إطلاقات وعوالم وأفلام ومنتجات وتجارب.')}<br/><span>{t('Certaines sont à vous. D’autres à nous.','Some are yours. Some are ours.','بعضها لكم. وبعضها لنا.')}</span></p><div className="ex-actions"><a className="ex-link" href="#escaped">{t('Voir ce qui s’est échappé','See what escaped','شاهد ما خرج')}<Arr down/></a><Go solid>{t('Parlons de votre projet','Let’s talk about your project','لنتحدث عن مشروعك')}</Go></div></div></section>
<section className="ex-wrap ex-selected" id="escaped"><Tag>01 / {t('POUR LES AUTRES','FOR OTHERS','للآخرين')}</Tag><Reveal><AnimatedHeading>{t('DES IDÉES','THINGS WE','أفكار')}<br/><em>{t('DEVENUES RÉELLES.','HELPED EXIST.','صارت واقعاً.')}</em></AnimatedHeading></Reveal><div className="ex-section-intro"><p>{t('Des idées devenues lancements, films, identités, campagnes, expériences — et tout ce qu’il fallait pour les faire exister.','Ideas we helped cross the line into reality. Launches, films, identities, campaigns, experiences and whatever the idea required.','أفكار ساعدناها على أن تصبح واقعاً. إطلاقات وأفلام وهويات وحملات وتجارب، وكل ما احتاجته الفكرة.')}</p><Go to="/work">{t('Explorer le travail','Explore our work','استكشف أعمالنا')}</Go></div><WorkObjects/></section>
<section className="ex-lab-section"><div className="ex-wrap"><Reveal><LabIntro/></Reveal><div className={'ex-loose-note '+(touched?'is-touched':'')}><span>FILM. CODE. AI. IMAGES.<br/>SOUND. OBJECTS. INTERFACES.<br/><em>Bad ideas. Good accidents.</em></span><button className="ex-hand" aria-label={t('Déplacer la note','Nudge the note','حرّك الورقة')} aria-pressed={touched} onClick={()=>setTouched(!touched)}><img src="/brand/pictorial.svg" alt=""/></button></div><p className="ex-lab-fates">{t('Certaines expériences meurent ici. D’autres deviennent des outils, des projets clients ou des produits.','Some experiments die here. Some become tools. Some become client work. Some become products.','بعض التجارب تنتهي هنا. وبعضها يصبح أدوات أو أعمال عملاء أو منتجات.')}</p><Go to="/lab">{t('Entrer dans le Lab','Enter the Lab','ادخل المختبر')}</Go></div></section>
<section className="ex-wrap ex-drops-teaser"><Tag>03 / {t('À NOUS','OURS','لنا')}</Tag><Reveal><AnimatedHeading>{t('TOUT CE QU’ON FAIT','NOT EVERYTHING','ليس لكل')}<br/>{t('N’A PAS','WE MAKE HAS','ما نصنعه')}<br/><em>{t('UN CLIENT.','A CLIENT.','عميل.')}</em></AnimatedHeading></Reveal><p>{t('Certaines idées méritent de nous appartenir. Produits numériques, objets, outils, formats, vêtements, jeux — ou quelque chose qui n’a pas encore de catégorie.','Some ideas deserve to belong to us. Digital products, objects, tools, formats, clothes, games — or things that do not have a category yet.','بعض الأفكار تستحق أن تخصنا. منتجات رقمية وأشياء وأدوات وصيغ وملابس وألعاب، أو أشياء لم تجد فئتها بعد.')}</p><Go to="/drops">{t('Voir les drops','See the drops','شاهد الإصدارات')}</Go></section><BusinessEngine/><HowThingsEscape/><Story/><Movement/><FinalCall/></div>;}
